const mongoose = require('mongoose');

var productSchema = new mongoose.Schema({
    title:{
        type:String,
        require:true,
        trim:true,
    },
    slug:{
        type:String,
        require:true,
        unique:true,
        lowercase:true,
    },
    description:{
        type:String,
        require:true,
    },
    price:{
        type:Number,
        require:true,
    },
    sold:{
        type:Number,
        default:0,
    },
    category:{
        type:String,
        require:true,
    },
    brand:{
        type:String,
        require:true,
    },
    quantity:{
        type:Number,
        require:true,
    },
    images:{
        type:Array
    },
    color:{
        type:String,
        require:true,
    },
    ratings:[
        {
            star:Number,
            postedby:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"User"
            }
        }
    ]
},{
    timestamps:true
})

module.exports = mongoose.model("Product",productSchema)